/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VehiclesRouteImport } from './routes/vehicles'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VehiclesSearchRouteImport } from './routes/vehicles.search'
import { Route as VehiclesListRouteImport } from './routes/vehicles.list'
import { Route as VehiclesAddRouteImport } from './routes/vehicles.add'
import { Route as ClientsSearchRouteImport } from './routes/clients.search'
import { Route as ClientsListRouteImport } from './routes/clients.list'
import { Route as ClientsAddRouteImport } from './routes/clients.add'

const VehiclesRoute = VehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesSearchRoute = VehiclesSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => VehiclesRoute,
} as any)
const VehiclesListRoute = VehiclesListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => VehiclesRoute,
} as any)
const VehiclesAddRoute = VehiclesAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => VehiclesRoute,
} as any)
const ClientsSearchRoute = ClientsSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ClientsRoute,
} as any)
const ClientsListRoute = ClientsListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => ClientsRoute,
} as any)
const ClientsAddRoute = ClientsAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => ClientsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/clients': typeof ClientsRouteWithChildren
  '/vehicles': typeof VehiclesRouteWithChildren
  '/clients/add': typeof ClientsAddRoute
  '/clients/list': typeof ClientsListRoute
  '/clients/search': typeof ClientsSearchRoute
  '/vehicles/add': typeof VehiclesAddRoute
  '/vehicles/list': typeof VehiclesListRoute
  '/vehicles/search': typeof VehiclesSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/clients': typeof ClientsRouteWithChildren
  '/vehicles': typeof VehiclesRouteWithChildren
  '/clients/add': typeof ClientsAddRoute
  '/clients/list': typeof ClientsListRoute
  '/clients/search': typeof ClientsSearchRoute
  '/vehicles/add': typeof VehiclesAddRoute
  '/vehicles/list': typeof VehiclesListRoute
  '/vehicles/search': typeof VehiclesSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/clients': typeof ClientsRouteWithChildren
  '/vehicles': typeof VehiclesRouteWithChildren
  '/clients/add': typeof ClientsAddRoute
  '/clients/list': typeof ClientsListRoute
  '/clients/search': typeof ClientsSearchRoute
  '/vehicles/add': typeof VehiclesAddRoute
  '/vehicles/list': typeof VehiclesListRoute
  '/vehicles/search': typeof VehiclesSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/clients'
    | '/vehicles'
    | '/clients/add'
    | '/clients/list'
    | '/clients/search'
    | '/vehicles/add'
    | '/vehicles/list'
    | '/vehicles/search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/clients'
    | '/vehicles'
    | '/clients/add'
    | '/clients/list'
    | '/clients/search'
    | '/vehicles/add'
    | '/vehicles/list'
    | '/vehicles/search'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/clients'
    | '/vehicles'
    | '/clients/add'
    | '/clients/list'
    | '/clients/search'
    | '/vehicles/add'
    | '/vehicles/list'
    | '/vehicles/search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ClientsRoute: typeof ClientsRouteWithChildren
  VehiclesRoute: typeof VehiclesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vehicles': {
      id: '/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof VehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/search': {
      id: '/vehicles/search'
      path: '/search'
      fullPath: '/vehicles/search'
      preLoaderRoute: typeof VehiclesSearchRouteImport
      parentRoute: typeof VehiclesRoute
    }
    '/vehicles/list': {
      id: '/vehicles/list'
      path: '/list'
      fullPath: '/vehicles/list'
      preLoaderRoute: typeof VehiclesListRouteImport
      parentRoute: typeof VehiclesRoute
    }
    '/vehicles/add': {
      id: '/vehicles/add'
      path: '/add'
      fullPath: '/vehicles/add'
      preLoaderRoute: typeof VehiclesAddRouteImport
      parentRoute: typeof VehiclesRoute
    }
    '/clients/search': {
      id: '/clients/search'
      path: '/search'
      fullPath: '/clients/search'
      preLoaderRoute: typeof ClientsSearchRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/clients/list': {
      id: '/clients/list'
      path: '/list'
      fullPath: '/clients/list'
      preLoaderRoute: typeof ClientsListRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/clients/add': {
      id: '/clients/add'
      path: '/add'
      fullPath: '/clients/add'
      preLoaderRoute: typeof ClientsAddRouteImport
      parentRoute: typeof ClientsRoute
    }
  }
}

interface ClientsRouteChildren {
  ClientsAddRoute: typeof ClientsAddRoute
  ClientsListRoute: typeof ClientsListRoute
  ClientsSearchRoute: typeof ClientsSearchRoute
}

const ClientsRouteChildren: ClientsRouteChildren = {
  ClientsAddRoute: ClientsAddRoute,
  ClientsListRoute: ClientsListRoute,
  ClientsSearchRoute: ClientsSearchRoute,
}

const ClientsRouteWithChildren =
  ClientsRoute._addFileChildren(ClientsRouteChildren)

interface VehiclesRouteChildren {
  VehiclesAddRoute: typeof VehiclesAddRoute
  VehiclesListRoute: typeof VehiclesListRoute
  VehiclesSearchRoute: typeof VehiclesSearchRoute
}

const VehiclesRouteChildren: VehiclesRouteChildren = {
  VehiclesAddRoute: VehiclesAddRoute,
  VehiclesListRoute: VehiclesListRoute,
  VehiclesSearchRoute: VehiclesSearchRoute,
}

const VehiclesRouteWithChildren = VehiclesRoute._addFileChildren(
  VehiclesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ClientsRoute: ClientsRouteWithChildren,
  VehiclesRoute: VehiclesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
